// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQBg_FcAhIcMRi5PsPbZF9B9ohMt4Te1U',
    appId: '1:35761630172:web:c1796626e714c24ce97d19',
    messagingSenderId: '35761630172',
    projectId: 'renbo-genai',
    authDomain: 'renbo-genai.firebaseapp.com',
    storageBucket: 'renbo-genai.firebasestorage.app',
    measurementId: 'G-TQKD414CD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQjlMRHgDVAklC8CUku_k-V0G1k4hZ2nU',
    appId: '1:35761630172:android:2e3411378118358ee97d19',
    messagingSenderId: '35761630172',
    projectId: 'renbo-genai',
    storageBucket: 'renbo-genai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJkMBFqqB-wwsQhvUTC-A1UVOOfF36ifc',
    appId: '1:35761630172:ios:95f578dd856ed27ae97d19',
    messagingSenderId: '35761630172',
    projectId: 'renbo-genai',
    storageBucket: 'renbo-genai.firebasestorage.app',
    iosBundleId: 'com.example.renbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJkMBFqqB-wwsQhvUTC-A1UVOOfF36ifc',
    appId: '1:35761630172:ios:95f578dd856ed27ae97d19',
    messagingSenderId: '35761630172',
    projectId: 'renbo-genai',
    storageBucket: 'renbo-genai.firebasestorage.app',
    iosBundleId: 'com.example.renbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQBg_FcAhIcMRi5PsPbZF9B9ohMt4Te1U',
    appId: '1:35761630172:web:8a091df2f970393ce97d19',
    messagingSenderId: '35761630172',
    projectId: 'renbo-genai',
    authDomain: 'renbo-genai.firebaseapp.com',
    storageBucket: 'renbo-genai.firebasestorage.app',
    measurementId: 'G-DWR0YHN8TX',
  );
}
