import 'package:hive/hive.dart';
import 'package:uuid/uuid.dart';

part 'journal_entry.g.dart'; // This file is generated by build_runner

@HiveType(typeId: 0)
class JournalEntry extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  String content;

  @HiveField(2)
  final DateTime timestamp;

  @HiveField(3)
  final String? emotion;

  @HiveField(4)
  String? imagePath;

  @HiveField(5)
  String? audioPath;
  
  @HiveField(6)
  List<String>? stickerIds;

  JournalEntry({
    required this.content,
    required this.timestamp,
    this.emotion,
    this.imagePath,
    this.audioPath,
    this.stickerIds,
  }) : id = const Uuid().v4();
}

